// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoccerCheckin.Web.Data;

#nullable disable

namespace SoccerCheckin.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502074549_RemovePlayerRecords")]
    partial class RemovePlayerRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoccerCheckin.Web.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByEmail")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("SoccerCheckin.Web.Models.ProgramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("UserSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId");

                    b.HasIndex("ProgramId", "UserSessionId")
                        .IsUnique();

                    b.ToTable("ProgramUsers");
                });

            modelBuilder.Entity("SoccerCheckin.Web.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MicrosoftDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("MicrosoftEmail")
                        .HasColumnType("text");

                    b.Property<string>("MicrosoftId")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("WeChatHeadimgUrl")
                        .HasColumnType("text");

                    b.Property<string>("WeChatNickname")
                        .HasColumnType("text");

                    b.Property<string>("WeChatOpenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MicrosoftEmail")
                        .IsUnique()
                        .HasFilter("\"MicrosoftEmail\" IS NOT NULL");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("SoccerCheckin.Web.Models.ProgramUser", b =>
                {
                    b.HasOne("SoccerCheckin.Web.Models.Program", "Program")
                        .WithMany("ProgramUsers")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerCheckin.Web.Models.UserSession", "UserSession")
                        .WithMany("ProgramUsers")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("SoccerCheckin.Web.Models.Program", b =>
                {
                    b.Navigation("ProgramUsers");
                });

            modelBuilder.Entity("SoccerCheckin.Web.Models.UserSession", b =>
                {
                    b.Navigation("ProgramUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
